export { SettingsPage } from './ui/pages/SettingsPage'
export { PreferencesProvider } from './data/stores/providers'
export { usePreferencesSnapshot } from './data/hooks/usePreferencesSnapshot'
export { LANGUAGE_TO_INTL } from './core/constants/Preferences.constants'
export type { AppLanguage, AppRegion, AppTheme } from './core/types/Preferences.types'